### ISSUE TITLE
[Documentation] Get images is not correct

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#9] opened 2022-05-31 10:03 UTC
### What happened?

Invalid module is referred here - Core instead of core 
https://www.pulumi.com/registry/packages/oci/api-docs/core/getimages/ 

### Steps to reproduce

https://www.pulumi.com/registry/packages/oci/api-docs/core/getimages/

### Expected Behavior

the module name should be correct - it's not Core but it's core.

### Actual Behavior

Its failing.

### Versions used

NA

### Additional context

<img width="647" alt="image" src="https://user-images.githubusercontent.com/23480999/171148543-cda5cffa-7d09-472a-aa94-650acbc44053.png">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-05-31 17:09
I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531 as this is the same code generation issue

**Closed by stack72** 2022-05-31 17:09 UTC
Labels: kind/bug, resolution/duplicate
