### ISSUE TITLE
OCI Deploymentpipeline import is failing

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#19] opened 2022-06-06 08:06 UTC
### What happened?

Tried importing the OCI Deploypipeline ,the imported pipeline code snippet is not having the correct module informations.

```
ocidevops_pipeline = oci.dev_ops.DeployPipeline("ocidevops_pipeline", < ===Invalid module dev_ops or dev.ops
    deploy_pipeline_parameters=oci.dev.ops.DeployPipelineDeployPipelineParametersArgs(
        items=[oci.dev.ops.DeployPipelineDeployPipelineParametersItemArgs(
            default_value="ns-node",
            description="A namespace for the deployment",
            name="namespace",
        )],
    ),
    description="Pipeline to deploy to OKE using devops and pulumi",
    display_name="pulumi_devops_deploypipeline",
    project_id="ocid1.devopsproject.oc1.iad.xx")
```

### Steps to reproduce

pulumi import oci:DevOps/deployPipeline:DeployPipeline test_deploy_pipeline "id"

### Expected Behavior

Imported definition  code should be usable 

### Actual Behavior

Invalid module dev_ops or dev.ops

### Versions used

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-06-06 08:32
Hi @RahulMR42

I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531

Paul

**Closed by stack72** 2022-06-06 08:32 UTC
Labels: kind/bug, resolution/duplicate
