### ISSUE TITLE
Invalid reference to module "ContainerEngine"

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#21] opened 2022-06-06 12:20 UTC
### What happened?

```
import pulumi
import pulumi_oci as oci

test_cluster_kube_config = oci.ContainerEngine.get_cluster_kube_config(cluster_id=oci_containerengine_cluster["test_cluster"]["id"], <== Invalid ContainerEngine
    endpoint=var["cluster_kube_config_endpoint"],
    expiration=var["cluster_kube_config_expiration"],
    token_version=var["cluster_kube_config_token_version"])
```

### Steps to reproduce

https://www.pulumi.com/registry/packages/oci/api-docs/containerengine/getclusterkubeconfig/

### Expected Behavior

Proper doc

### Actual Behavior

Invalid module ``'pulumi_oci' has no attribute 'ContainerEngine'
``

### Versions used

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-06-06 15:21
Hi @RahulMR42

I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531

Paul

**Closed by stack72** 2022-06-06 15:21 UTC
Labels: kind/bug, resolution/duplicate
