### ISSUE TITLE
Devops build stage is not working as expected .

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#16] opened 2022-06-03 12:07 UTC
### What happened?

```
build_stage_appbuild = oci.dev_ops.BuildPipelineStage("build_stage_appbuild",
    build_pipeline_id="ocid1.devopsbuildpipeline.oc1.iad.xxxx",
    build_pipeline_stage_predecessor_collection=oci.dev.ops.BuildPipelineStageBuildPipelineStagePredecessorCollectionArgs(
        items=[oci.dev.ops.BuildPipelineStageBuildPipelineStagePredecessorCollectionItemArgs(
            id="ocid1.devopsbuildpipeline.oc1.iad.xxxx",
        )],
    ),
    build_pipeline_stage_type="BUILD",
    build_source_collection=oci.dev.ops.BuildPipelineStageBuildSourceCollectionArgs(
        items=[oci.dev.ops.BuildPipelineStageBuildSourceCollectionItemArgs(
            branch="main",
            connection_type="DEVOPS_CODE_REPOSITORY",
            name="node_express",
            repository_id="ocid1.devopsrepository.oc1.iad.xxx",
            repository_url="https://devops.scmservice.us-ashburn-1.oci.oraclecloud.com/namespaces/"
        )],
    ),
    description="Build your application.",
    display_name="BuildStage",
    image="OL7_X86_64_STANDARD_10",
    primary_build_source="node_express",
    stage_execution_timeout_in_seconds=36000)

```
The code generated are wrong , there are no modules like dev_ops or dev.ops must be devops

### Steps to reproduce

pulumi import oci:DevOps/buildPipelineStage:BuildPipelineStage test_build_pipeline_stage "id"

### Expected Behavior

Should be able to use exported code as is .

### Actual Behavior

Wrong devops module.

### Versions used

na

### Additional context

Its a terraform - pulumi bridge issue.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-06-03 13:09
Hi @RahulMR42 

I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531

Paul

**Closed by stack72** 2022-06-03 13:09 UTC
Labels: kind/bug, resolution/duplicate
