### ISSUE TITLE
Annoying `in privateKey section`

### ISSUE THREAD

**Issue by mikucat0309** [pulumi/pulumi-oci#276] opened 2023-11-29 15:16 UTC
### What happened?

Pulumi repeats `in privateKey section` 330 times, and it's very annoying

### Example

Command:
```sh
pulumi up
```

Output:

```
Previewing update (prod):
     Type                 Name                 Plan     Info
     pulumi:pulumi:Stack  Infrastructure-prod           2 warnings; 1 message

Diagnostics:
  pulumi:pulumi:Stack (Infrastructure-prod):
    warning: using pulumi-language-nodejs from $PATH at /run/current-system/sw/bin/pulumi-language-nodejs
    warning: using pulumi-language-nodejs from $PATH at /run/current-system/sw/bin/pulumi-language-nodejs

    in privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey sectionin privateKey section

Resources:
    12 unchanged

Do you want to perform this update? no
confirmation declined, not proceeding with the update
```

### Output of `pulumi about`

```
warning: using pulumi-language-nodejs from $PATH at /run/current-system/sw/bin/pulumi-language-nodejs
warning: using pulumi-language-nodejs from $PATH at /run/current-system/sw/bin/pulumi-language-nodejs
CLI          
Version      3.90.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown
oci     1.16.0

Host     
OS       darwin
Version  14.1
Arch     arm64

This project is written in nodejs: executable='/run/current-system/sw/bin/node' version='v20.9.0'

Current Stack: organization/Infrastructure/prod

TYPE                                              URN
pulumi:pulumi:Stack                               urn:pulumi:prod::Infrastructure::pulumi:pulumi:Stack::Infrastructure-prod
pulumi:providers:oci                              urn:pulumi:prod::Infrastructure::pulumi:providers:oci::default_1_16_0
oci:Identity/compartment:Compartment              urn:pulumi:prod::Infrastructure::oci:Identity/compartment:Compartment::compartment
oci:Core/vcn:Vcn                                  urn:pulumi:prod::Infrastructure::oci:Core/vcn:Vcn::service
oci:ObjectStorage/bucket:Bucket                   urn:pulumi:prod::Infrastructure::oci:ObjectStorage/bucket:Bucket::bucket
oci:Core/subnet:Subnet                            urn:pulumi:prod::Infrastructure::oci:Core/subnet:Subnet::publicSubnet
oci:Core/subnet:Subnet                            urn:pulumi:prod::Infrastructure::oci:Core/subnet:Subnet::privateSubnet
oci:Core/defaultSecurityList:DefaultSecurityList  urn:pulumi:prod::Infrastructure::oci:Core/defaultSecurityList:DefaultSecurityList::DefaultSecurityList
oci:Core/securityList:SecurityList                urn:pulumi:prod::Infrastructure::oci:Core/securityList:SecurityList::PrimarySecurityList
oci:ObjectStorage/storageObject:StorageObject     urn:pulumi:prod::Infrastructure::oci:ObjectStorage/storageObject:StorageObject::object
oci:Core/image:Image                              urn:pulumi:prod::Infrastructure::oci:Core/image:Image::image
oci:Core/instance:Instance                        urn:pulumi:prod::Infrastructure::oci:Core/instance:Instance::primary
oci:Core/shapeManagement:ShapeManagement          urn:pulumi:prod::Infrastructure::oci:Core/shapeManagement:ShapeManagement::shape-compat-VM.Standard.A1.Flex


Found no pending operations associated with prod

Backend        
Name           DESKTOP-MIKUCAT.local
URL            file://~
User           mikucat
Organizations  
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/oci     1.16.0
@pulumi/pulumi  3.94.2
@types/node     20.10.0
prettier        3.1.0

Pulumi locates its logs in /var/folders/xs/q5ds6ys13z9_mmfp3lxvbys00000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2023-11-29 16:50
Hey @mikucat0309. That sounds super annoying. Can you please provide a pulumi program that reproduces the problem?

**Comment by iwahbe** [comment] 2023-12-02 00:48
I don't have easy access to a set of OCI keys, so it's not easy for me to test this. I'm going to try releasing a new version of this provider, since we have made a bunch of improvements to the libraries it uses in the last month. I'm hoping that this will go away. If the bug persists on `v1.16.1`, please let me know.

**Comment by v2kk** [comment] 2023-12-03 17:00
I'm still facing the same annoying message after upgrade to 1.16.1. My runtime is python with the same configuration as @mikucat0309

**Comment by mjeffryes** [comment] 2024-04-19 00:14
Looks like this was an upstream bug in the tf provider fixed in this commit: https://github.com/oracle/terraform-provider-oci/commit/f042629b686d6db158ff5d8144a7103212e66c8a

Recent versions of this provider should not have this problem

**Closed by mjeffryes** 2024-04-19 00:14 UTC
Labels: kind/bug, resolution/fixed
