### ISSUE TITLE
Deploy artifact import is not correct

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#17] opened 2022-06-03 12:59 UTC
### What happened?

Did a pulumi import of deploy artifact and its not correct on the format and build param.

```
artifact_containerrepo = oci.dev_ops.DeployArtifact("artifact_containerrepo", < == Invalid module name dev_ops or dev.ops
    argument_substitution_mode="SUBSTITUTE_PLACEHOLDERS",
    deploy_artifact_source=oci.dev.ops.DeployArtifactDeployArtifactSourceArgs(
        deploy_artifact_source_type="OCIR",
        image_uri=f"us-ashburn-1.ocir.io/fahdabidiroottenancy/mr_devops_pulumi_oke_repo:{buildru_n__hash}", <==The values is not correct its actually BUILDRUN_HASH 
    ),
    deploy_artifact_type="DOCKER_IMAGE",
    display_name="pulumi_devops_containerrepo_artifact",
    project_id="ocid1.devopsproject.oc1.iad.xxx")

```

### Steps to reproduce

pulumi import oci:DevOps/deployArtifact:DeployArtifact test_deploy_artifact "id"

### Expected Behavior

Imported modules should be able to use as it 

 - module name should beDevOpss 
 - parametertosubstitutee must be as defined in the actual artifact 
 - 
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/23480999/171858484-8446902d-0f36-4f10-823a-2bfe2b8d2f23.png">

### Actual Behavior

code snippet is not correct.

### Versions used

na

### Additional context

Its a pulumi-terraform bridge issue 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-06-03 13:08
Hi @RahulMR42 

I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531

Paul

**Closed by stack72** 2022-06-03 13:08 UTC
Labels: kind/bug, resolution/duplicate
