### ISSUE TITLE
[Import Failure] No module - container_engine

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#7] opened 2022-05-30 12:38 UTC
### What happened?

Did a pulumi import of oke and got the resource definition as below 

```test_cluster = oci.container_engine.Cluster("test_cluster",
                                                        compartment_id=config.get('compartment_ocid'),
                                                        endpoint_config=oci.container.engine.ClusterEndpointConfigArgs(
                                                            is_public_ip_enabled=config.get('oke_is_public_ip_enabled'),
                                                            subnet_id="ocid1.subnet.oc1.iad.aaaaaaa
```
while applying back got an error 

```
 pulumi:pulumi:Stack (pulumi-python-oci-devops-oke-oci-devops-oke):
    OKE Cluster creation failed module 'pulumi_oci' has no attribute 'container_engine'
 
    error: preview failed
 


```

### Steps to reproduce

rahulmr_in@rahulmr_in-mac pulumi_oci_devops % pulumi import oci:ContainerEngine/cluster:Cluster test_cluster "ID"

### Expected Behavior

Import should work for further actions too, and in the oci lib there is no module called container_engine but it is container engine 

### Actual Behavior

OKE import is as below ...

test_cluster = oci.container_engine.Cluster("test_cluster",
    compartment_id="ocid1.compartment.oc1..aaaaaaaalmc42p5bsqbfo5jkle7uy7bwnlazr7ghw26qorsidrwbl6mk6xva",
    endpoint_config=oci.container.engine.ClusterEndpointConfigArgs(

### Versions used

CLI          
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME    VERSION
oci     0.1.1
python  unknown

Host     
OS       darwin
Version  11.6.3
Arch     x86_64

This project is written in python (/usr/bin/python3 v3.8.9)

Current Stack: oci-devops-oke

TYPE                                 URN
pulumi:pulumi:Stack                  urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::pulumi:pulumi:Stack::pulumi-python-oci-devops-oke-oci-devops-oke
pulumi:providers:oci                 urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::pulumi:providers:oci::default_0_1_1
oci:ContainerEngine/cluster:Cluster  urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::oci:ContainerEngine/cluster:Cluster::test_cluster
oci:Core/vcn:Vcn                     urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::oci:Core/vcn:Vcn::test_vcn

Found no pending operations associated with oci-devops-oke

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/RahulMR42
User           RahulMR42
Organizations  RahulMR42

NAME        VERSION
pip         22.1.1
pulumi-oci  0.1.1
setuptools  62.3.2
wheel       0.37.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RahulMR42** [comment] 2022-05-30 12:46
Also if you may see for the imports its returning components with the '
''container.engine 
 endpoint_config=oci.container.engine.ClusterEndpoint <<<== 
''', 
indeed that needs to correct.

**Comment by stack72** [comment] 2022-05-31 17:12
I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531 as this is the same code generation issue

**Closed by stack72** 2022-05-31 17:12 UTC
Labels: kind/bug, resolution/duplicate
