### ISSUE TITLE
[Documentation] GetAvailabilityDomains ,invalid documentation

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#10] opened 2022-05-31 10:34 UTC
### What happened?

https://www.pulumi.com/registry/packages/oci/api-docs/identity/getavailabilitydomain/ 

- No module called Identity , it must be identity 

### Steps to reproduce

https://www.pulumi.com/registry/packages/oci/api-docs/identity/getavailabilitydomain/

### Expected Behavior

Module name should be correct

### Actual Behavior

Invalid module  -case /typo 

### Additional context

<img width="795" alt="image" src="https://user-images.githubusercontent.com/23480999/171154387-6a84fa8b-437c-4b40-8675-05ee00b2429d.png">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-05-31 17:08
I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531 as this is the same code generation issue

**Closed by stack72** 2022-05-31 17:08 UTC
Labels: kind/bug, resolution/duplicate
