### ISSUE TITLE
Import / Create failure - OKE nodepool 

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#8] opened 2022-05-30 13:11 UTC
### What happened?

Documentation - https://www.pulumi.com/registry/packages/oci/api-docs/containerengine/nodepool/ 
```
test_node_pool = oci.container_engine.NodePool("testNodePool",
    cluster_id=oci_containerengine_cluster["test_cluster"]["id"],
    compartment_id=var["compartment_id"],
    kubernetes_version=var["node_pool_kubernetes_version"],
    node_shape=var["node_pool_node_shape"],
    defined_tags={
        "Operations.CostCenter": "42",

```

Error 

No module container_engine or container.engine 

### Steps to reproduce

Refer above

### Expected Behavior

Able to export and use node pool resources.

### Actual Behavior

Its failing as the actual module name is container engine while the import or documentation gives wrong values 

### Versions used

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-05-31 17:13
I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531 as this is the same code generation issue

**Closed by stack72** 2022-05-31 17:13 UTC
Labels: kind/bug, resolution/duplicate
