### ISSUE TITLE
Oci deployment stage import failing 

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#20] opened 2022-06-06 09:14 UTC
### What happened?

Imported code snippet is invalid 
```
deployto_oke = oci.dev_ops.DeployStage("deployto_oke", < Invalid module dev.ops or dev_ops
    deploy_pipeline_id="ocid1.devopsdeploypipeline.oc1.iad.xxx",
    deploy_stage_predecessor_collection=oci.dev.ops.DeployStageDeployStagePredecessorCollectionArgs(
        items=[oci.dev.ops.DeployStageDeployStagePredecessorCollectionItemArgs(
            id="ocid1.devopsdeploypipeline.oc1.iad.xxx",
        )],
    ),
    deploy_stage_type="OKE_DEPLOYMENT",
    description="Apply asdasd",
    display_name="Apply",
    kubernetes_manifest_deploy_artifact_ids=["ocid1.devopsdeployartifact.oc1.iad.xxx"],
    namespace="default",
    oke_cluster_deploy_environment_id="ocid1.devopsdeployenvironment.oc1.iad.xxx",
    rollback_policy=oci.dev.ops.DeployStageRollbackPolicyArgs(
        policy_type="AUTOMATED_STAGE_ROLLBACK_POLICY",
    ))

```

### Steps to reproduce

pulumi import oci:DevOps/deployStage:DeployStage test_deploy_stage "id"

### Expected Behavior

Code should be usable as is .

### Actual Behavior

Invalid module ,must be devops.

### Versions used

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-06-06 10:35
Hi @RahulMR42

I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531

Paul

**Closed by stack72** 2022-06-06 10:35 UTC
Labels: kind/bug, resolution/duplicate
