### ISSUE TITLE
OCI Pulumi invalid module Objectstorage

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#18] opened 2022-06-03 13:33 UTC
### What happened?

 'pulumi_oci' has no attribute 'ObjectStorage' when using it with oci.Objectstorage 

The valid module should be objectstorage 

### Steps to reproduce

```
import pulumi
import pulumi_oci as oci

test_namespace = oci.ObjectStorage.get_namespace(compartment_id=var["compartment_id"])
```

### Expected Behavior

Should return the namespace

### Actual Behavior

Failing the execution ,invalid module ObjectStorage

### Versions used

na

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-06-04 13:10
Hi @RahulMR42

I am going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/531

Paul

**Closed by stack72** 2022-06-04 13:10 UTC
Labels: kind/bug, resolution/duplicate
